<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>agc</string>
	</array>
	<key>name</key>
	<string>AGC Assembly</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Comments</string>
			<key>match</key>
			<string>#.*</string>
			<key>name</key>
			<string>comment.agc_assembly</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.agc_assembly</string>
	<key>uuid</key>
	<string>fb9fa55a-903a-4291-8e6f-bc8fbfafbe38</string>
</dict>
</plist>
