<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>aea</string>
		<string>ags</string>
	</array>
	<key>name</key>
	<string>AGS Assembly</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Comments</string>
			<key>match</key>
			<false/>
			<key>name</key>
			<string>comment.ags</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ags</string>
	<key>uuid</key>
	<string>ebcb89b7-fbf9-467d-90ec-7ab247800e0c</string>
</dict>
</plist>
